[params]
    description = "Un sitio web de la Asociación de Propietarios para facilitar eventos y comunicación para el vecindario"
    show_post_dates = false


    [params.footer]

        [[params.footer.links]]
            header = "Preguntas Frecuentes"
        [[params.footer.links.links]]
            title = "¿Cómo puedo..."
            url = "faq"

        [[params.footer.links]]
            header = "Próximamente..."
        [[params.footer.links.links]]
            title = "Pagos"
            url = "#"

        [params.footer.contact_form]
            enabled = true
            header = "Contactar a la Junta"
            action = "https://formspree.io/f/mdoqzajr"
