baseURL = "https://cambridgevillagehoa.com"
languageCode = "en-us"
title = "Cambridge Village HOA"
theme = "hugo-arcana"
copyright = "© Cambridge Village HOA Inc"

defaultContentLanguage = "en"
[languages]
    [languages.en]
        languageName = "English"
        weight = 1
    [languages.es]
        languageName = "Español"
        weight = 2

[taxonomies]
    tag = "tags"

[params]
    description = "A Home Owner Association web site to facilitate events and communication for the neighborhood"
    show_post_dates = false


    [params.footer]

        [[params.footer.links]]
            header = "Frequently Asked Questions"
        [[params.footer.links.links]]
            title = "How do I..."
            url = "faq"

        [[params.footer.links]]
            header = "Coming soon..."
        [[params.footer.links.links]]
            title = "Payments"
            url = "#"

        [params.footer.contact_form]
            enabled = true
            header = "Get In Touch"
            action = ""
